### ISSUE TITLE
§3.2.4: Line 3 in example "stamps" uses unexplained syntax

### ISSUE THREAD

**Issue by darijgr** [math-comp/mcb#17]
I'm talking of this:
`elim: n {-2}n (leqnn n) =>[|n IHn]; first by case.`
I have really no idea what is happening between the `elim` and the `=>` here. Apparently it magically transforms the goal into a version of it such that inducting over the latter is equivalent to strongly inducting over the former; at least the `leqnn n` is definitely relevant for that. But what is the `{-2}n` achieving? (I understand that `{-2}` means something like "all except for the 2nd occurrence" -- which should probably be explained though --, but what exactly is being done here? Generally, what does `elim:` do when given several arguments? What order are they traversed, and what is done to them?

(I can get through the example if I replace the line quoted above by
`have: forall n0 : nat, n0 <= n -> 12 <= n0 -> exists s4 s5 : nat, s4 * 4 + s5 * 5 = n0; last first.`
`  move=> Strong_Version. apply (Strong_Version n (leqnn n)).`
`elim: n => [|n IHn]; first by case.`
But this is ugly...)

**Comment by anton-trunov** [comment]
It is explained in detail in [this](https://hal.inria.fr/inria-00407778/file/RT-367.pdf) tutorial, p. 26.

**Comment by gares** [comment]
It is the last sentence of 3.2.2.  I guess we need to put a pointer back to that paragraph, and quickly recall there that `:` pushes on the stack its arguments, right to left...

**Comment by darijgr** [comment]
Ah, thanks! I'm working this into #10 right now. But note that the right-to-left pushing is not the whole story; it is also important that "elim:" is applied to the leftmost argument.
