### ISSUE TITLE
Chapter 8 & 9 are empty

### ISSUE THREAD

**Issue by laygr** [math-comp/mcb#2]
I don't know if they're a work in progress or if there really is an error, but chapter 8 and chapter 9 of the [pdf ](https://math-comp.github.io/mcb/book.pdf) appear empty.

**Comment by gares** [comment]
Yep, part 3 is "in progress".  Thanks for the heads up anyway.

**Comment by amahboubi** [comment]
Part 3 will not be available in a near future. Therefore I am closing the issue...
