### ISSUE TITLE
Introduce first class citizen before using it

### ISSUE THREAD

**Issue by MarisaKirisame** [math-comp/mcb#3]
In the book, it is said that 'types are first class citizen', without really explaining what it is. It might confused the 'mathematically inclined reader'.

**Comment by amahboubi** [comment]
Thanks for pointing this Marisa! We will address this issue as soon as possible.

**Comment by MarisaKirisame** [comment]
NP. Really glad you try to make coq more approachable to outsider.

**Comment by amahboubi** [comment]
Hi @MarisaKirisame! A series of commits (0a01fabe71a004f293ad77b6580253bf3a45ee15, a2c8d9903dacc7fba294a47a884945f21784250a, 983705007ed7e0f6ba6302137634c65044b76dda, 9b3e902ac9fa40a19e373993e85edf33c44c7018) addresses this issue. So I am closing it for now. Thanks for helping us improving this text!

**Comment by MarisaKirisame** [comment]
👍
