### ISSUE TITLE
overlapping margin notes on p. 25

### ISSUE THREAD

**Issue by remysucre** [math-comp/mcb#35]
There seems to be 2 margin notes on top of each other at the bottom of p. 25 in the version linked from https://math-comp.github.io/mcb/book.pdf

**Comment by remysucre** [comment]
The version compiled from the latest commit does not seem to have the notes. Not sure if they are meant for the reader or the authors.

**Comment by gares** [comment]
Thanks for reporting, they are leftovers.  And all margin notes should go in the final version.
So yes, we are going to remove them.
