### ISSUE TITLE
§2.4: the main goal actually mentions the “divides” predicate

### ISSUE THREAD

**Issue by mituharu** [math-comp/mcb#41]
The 5th paragraph in Section 2.4 says:
> In fact, optionally rewriting with `dvdn_fact` on all goals affects only the side condition, since the main goal mentions no  “divides” predicate.

But the main goal at this stage below actually mentions the “divides” predicate:
```
  m, p : nat
  prime_p : prime p
  leq_p_m : p <= m
  ============================
  ~~ (p %| 1)
```

**Comment by gares** [comment]
thanks!
