### ISSUE TITLE
Ch. 6: (n : nat) + (i : ’I_7) can't be smaller than 7

### ISSUE THREAD

**Issue by anton-trunov** [math-comp/mcb#47]
> Integers and integers smaller than 7 are interchangeable data: if `(n : nat)` and `(i : ’I_7)` one can clearly add `n` to `i`, and eventually show that the sum is still smaller than 7.

The last part of the sentence should probably be removed, since the paragraph mentions `(i+n %| 7)`.

**Comment by gares** [comment]
thanks! in Italian eventually means possibly ;-)
