### ISSUE TITLE
Example in chapter 2, sect. 2.3.3

### ISSUE THREAD

**Issue by anton-trunov** [math-comp/mcb#5]
The example starting on [line 1435](https://github.com/math-comp/mcb/blob/296e0d120eec9a22e7dc1e14267170e24d970278/tex/chProofs.tex#L1435) needs some corrections.

1. ``Lemma example m p : prime p -> p %| m `! + 1 -> m < p.`` suddenly turns into ``Lemma example m p : prime p -> p %| m `! + 1 -> ~~ (p <= m).``, then it reverts to the original version.
2. The text mentions `contraLR` lemma, but `contraL` appears instead.

Also, could the *real* `dvdn_fact` lemma be used instead of a wrapper defined in the text? 
 - text: ``Lemma dvdn_fact  m n : 0 < m -> m ≤ n → m %| n`!.``
 - library: ``Lemma dvdn_fact m n : 0 < m ≤ n → m %| n`!.``

**Comment by amahboubi** [comment]
You are absolutely right, this example is really nonsensical. Thanks for pointing this.

**Comment by gares** [comment]
Minor note: IIRC the "simplified" statement of `dvdn_fact` was needed since notation `a < b < c` was not presented yet.  To be checked if it is still the case.

**Comment by anton-trunov** [comment]
Good point.

I think it wasn't presented at that point, but all the tools are given: Chapter 1 introduces the `Locate` command:

>The `Locate` command can be used to reveal the actual term represented by a notation. In order to understand the meaning of an unknown notation like for instance `(a <= b <= c)`, one can use the `Locate` command to uncover the symbols it involves.

And the book provides the output:

```Coq
"m <= n <= p" := andb (leq m n) (leq n p)    : nat_scope
"m <= n < p" := andb (leq m n) (leq (S n) p)
```

**Comment by anton-trunov** [comment]
I should point out that #9 addresses the `m < p` / `~~ (p <= m)` part of this issue.

**Comment by amahboubi** [comment]
Almost. It is a good start but a few glitches remain after merging #9...

**Comment by darijgr** [comment]
I believe #10 deals with the rest of m < p vs. ~~ (p <= m).

**Comment by amahboubi** [comment]
Oh thanks @darijgr! We will postpone the resolution of this issue to after the merge of #10 then.

**Comment by gares** [comment]
I think all issues are solved now.
