### ISSUE TITLE
"Eval compute in" vs "Compute" ?

### ISSUE THREAD

**Issue by anton-trunov** [math-comp/mcb#50]
`Eval compute in` is introduced in chapter 1. In my opinion, the syntax is bit verbose for the newcomer and also does not look very much like `About`, `Check`, and `Print`. There is a simpler alternative: `Compute`, which is an alias of `Eval vm_compute in`.

What do you think of using `Compute` throughout the book?

(`Eval hnf in` could be explained a bit later to make things a bit smoother at the beginning)

**Comment by gares** [comment]
I think it is a good idea. @amahboubi what do you think?

**Comment by amahboubi** [comment]
Hi, I agree. Thanks for this suggestion!

**Comment by anton-trunov** [comment]
Thank *you*!

**Comment by ybertot** [comment]
The reason for using Eval compute in instead of Compute was that "Compute" was not available in jscoq at the time of writing.

**Comment by anton-trunov** [comment]
@ybertot Oh, this is interesting, thank you. It seems the book does not mention jsCoq. It could probably advertise this possibility more. I think it would make the life of newcomers much easier. I recently gave a talk using MathComp and almost everybody had trouble installing the library natively. (I provided a preconfigured Ubuntu-based virtual machine, but people seemed to be reluctant to use it; and I completely forgot about the Web-based tooling).

**Comment by gares** [comment]
I did check yesterday before applying the change and `Compute` works on jscoq. I think I've see a PR introducing a fallback to `cbv` when `vm_compute` is not available.

**Comment by ejgallego** [comment]
Indeed now coq has a flag to use a fallback from  vm compute.

**Comment by ejgallego** [comment]
This was specially needed as some tactics can insert vmcasts.
