### ISSUE TITLE
Sect. 1.3.3 Option and pair data types: introduce irrefutable pattern-matching?

### ISSUE THREAD

**Issue by anton-trunov** [math-comp/mcb#53]
The section defines `fst` function as follows:
```coq
Definition fst A B (p : pair A B) :=
  match p with mk_pair x _ => x end.
```

This might be an opportunity to introduce irrefutable pattern-matching construction:
```
Definition fst A B (p : A * B) : A :=
  let: (a, _) := p in a.
```
(probably after the original more verbose version)

Sect. 1.3.4 shows this construction, but still it might make sense to introduce it earlier.

**Comment by gares** [comment]
I'm going to close this one. Irrefutable pattern matching is explained in the section immediately following the one defining pairs, so I guess it would not change things much.
