### ISSUE TITLE
Difficulty with using references to Coq manual 

### ISSUE THREAD

**Issue by pmundkur** [math-comp/mcb#60]
References to numbered sections and chapters of the Coq manual are difficult to interpret/follow-up since it appears that the reference manual is now web-only without a PDF version available.

**Comment by anton-trunov** [comment]
Hi @pmundkur,

> reference manual is now web-only without a PDF version available.

@cpitclaudel knows how to generate a PDF version of the manual, but I cannot find the link to that PDF. 
Strangely enough I can search stuff in the (slightly outdated) PDF version of the manual he provided, but not in Sphinx.
Here is a relevant issue: https://github.com/coq/coq/issues/7500.

**Comment by pmundkur** [comment]
good to know, thanks @anton-trunov
