### ISSUE TITLE
remove exercises

### ISSUE THREAD

**Issue by gares** [math-comp/mcb#75]
move them to a companion teaching material

**Comment by siraben** [comment]
Where can I find that companion material?

**Comment by gares** [comment]
in the end, it was never released.
But some code of the exercises in the coq/ folder (you can play it online from the book site).
You can also look here:
- https://team.inria.fr/marelle/en/teaching/
- https://sites.google.com/view/2018eutypesschool/tassi

**Comment by siraben** [comment]
Thanks, I'm using this book to learn as well so those exercises are helpful. I think it would be good to have some exercises in the book so the reader can check their understanding.

**Comment by gares** [comment]
We had them, they are probably still there commented out. We run out of energy, they still needed polishing and some chapters just had no exercises, so we removed them.

We would be happier to have them back, but as I said, some work is needed.
